### ISSUE TITLE
USER STORY: Site administrator access

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#15]
As a **site administrator** I can **create/read/update and delete ski resorts** so that **I can manage the app content**.

### **Acceptance Criteria**
- View all ski resorts at the admin page
- Manage all ski resorts in one place
- Button option for creating a resort, viewing/reading, update existing or deleting resort.

### **Tasks**
- [x] Make all ski resorts visible in the admin panel
- [x] Make form to create resort and demand list of details for each resort
- [x] Create button for all options i.e create, read, update and delete
