### ISSUE TITLE
USER STORY: Log in and out

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#2]
As a **site user** I can **log in and out of my account** so that **I can keep my account secure**.

### **Acceptance Criteria**
- Log in button is visable on main page
- Log out button is visable on admin page
- User is automatically logged out when they are inactiv for 10 minutes

### **Tasks**
- [x] Make log in button that redirects to log in page / or window
- [x] A mail and password input field is inquired
- [x] Verify input fields and then redirect user to admin page

**Comment by TheresLundqvist** [comment]
User Story completed.
