### ISSUE TITLE
USER STORY: Site declaration 

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#20]
As a **site user** I can **immediately understand the purpose of the site** so that **I can decide if it meets my needs**

**Comment by TheresLundqvist** [comment]
**Acceptance Criteria**
- Main view declares site purpose
- All resorts accessable from main
- Inspiring ski photos beside declaration

**Tasks**
- [x] Declare site purpose
- [x] View all link next to declaration
- [x] Hero images carousel with overlay text declaration

**Comment by TheresLundqvist** [comment]
User story completed.
