### ISSUE TITLE
USER STORY: Intuitive site navigation

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#21]
As a **site user** I can **intuitively navigate around the site** so that **I can easily find content**.

### **Acceptance Criteria**
- Comment and rating option underneath each resort
- Log in and search bar at top of main page
- Toggle menu for mobile view
- All navigation options underneath navbar in desktop view

### **Tasks**
- [x] Create comment and rating button for resort pages
- [x] Make all approved comments and ratings visable underneath each resort
- [x] Add log in and search bar in header
- [x] Create toggle menu for mobile view
- [x] Add links to all pages underneath navbar

**Comment by TheresLundqvist** [comment]
User story completed.
