### ISSUE TITLE
USER STORY: Comment ski resorts

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#23]
As a **site user** I can **comment on ski resorts** so that **I can share my experience with others**.

### **Acceptance Criteria**
- Input field for comments
- Option to comment under each resort
- Show which user made comment
- Admin must approve comment before appearing on site

### **Tasks**
- [x] Create a comment model 
- [x] Add function so comments appear only after admin approve
- [x] Create comment form
