### ISSUE TITLE
USER STORY: Approve comments

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#25]
As a **site admin** I can **approve comments** so that **no objectionable comments is shown**.

### **Acceptance Criteria:**
- Show all new comments in admin page
- Make comments visable on page only after approval from Admin

### **Tasks**
- [x]  Create comment model
- [x] Create action approve_comments for Admin
- [x] Ad function so comment becomes visable after approval
