### ISSUE TITLE
USER STORY: Register account

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#3]
As a **site user** I can **register an account** so that **I can add/edit/delete** comments I made.

### **Acceptance Criteria**
- The sign up button is visable on main page
- Allow email addresses in format name@mail.com
- Verify password fields is not longer than 20 characters
- Verify that the password field is not shorter than 6 characters

### **Tasks**
- [x] Create sign up button that redirects user to sign up page
- [x] Add input fields on sign up page for for all details required for new registration
- [x] Make input fields required
- [x] Verify that input field are made with valid characters and the right length

**Comment by TheresLundqvist** [comment]
User story completed.
