### ISSUE TITLE
USER STORY: List of resorts

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#6]
As a **site user** I can **see a list with all ski resorts** so that **I can choose a resort to visit**.

### **Acceptance Criteria**
- View all resorts options in navigation
- List contains all published resorts
- Shows name, minimized image, average rating and country of the resort
- User descides which resort to get a full view of

### **Tasks**
- [x] Create "View all"-link 
- [x] Filter to only show published resorts
- [x] Customize list view to only show desired details
- [x] Make resort name a link that redirects user to full view

**Comment by TheresLundqvist** [comment]
User story completed.
