### ISSUE TITLE
USER STORY: Star rating

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Ski-resorts#9]
As a **site user** I can **give ski resorts star rating** so that **other users can make a better assessment**.

### **Acceptance Criteria**
- Star icon for rating
- Visable average rating for every resort
- Site user can add rating in resort detail
- Admin can view rating in admin panel

### **Tasks**
- [x] Add font awesome star icon
- [x] Function that generates average star rating
- [x] Clickable star icon adds to the average counter 
- [x] Display star rating in admin panel

**Comment by TheresLundqvist** [comment]
User Story completed.
